### ISSUE TITLE
Todo before phpBB 3.1 release

### ISSUE THREAD

**Issue by jaroslw** [inventea/we_clearblue#5]
- [x] Update to phpBB 3.1.8
- [x] Invisible notifications box content
- [x] Private messages -> PM link on mobiles
- [x] Test post attachments, images, quotes etc.
- [x] Test avatars
- [x] Update changelog
- [x] Update readme
- [x] Change lastpost column backgrounds for small devices
- [x] Username colour in posts and user manu bar

**Comment by seanieb** [comment]
Love this. Thank you! I made a donation via Paypal, have a beer on me.

**Comment by jaroslw** [comment]
Thank you! I've just prepared preview: https://inventea.com/phpbb/3.1/we_clearblue
